const images = {
    backgroundLogin: require('./imgs/hero_bg_5.jpg'),
    logoFacebook: require('./imgs/facebook.png'),
    logoGoogle: require('./imgs/google.png'),
    logoApple: require('./imgs/apple.png'),
    logoShop: require('./imgs/logoShop.png'),
    banner1: require('./imgs/hero_bg_6.jpg'),
    banner2: require('./imgs/hero_bg_7.jpg'),
    banner3: require('./imgs/banner3.png'),
    banner4: require('./imgs/banner4.png'),
    banner5: require('./imgs/banner5.png'),
    banner7: require('./imgs/banner7.jpg'),
    clockImg: require('./imgs/clock.png'),
    jacketImg: require('./imgs/jacket.png'),
    instagram: require('./imgs/instagram.png'),
    clothesImg: require('./imgs/clother.png'),
    glassesImg: require('./imgs/glasses.png'),
    userReview1: require('./imgs/review1.png'),
    cartProduct1: require('./imgs/cartProduct1.png'),
    bannerFooter1: require('./imgs/bannerFooter1.png'),
    bannerFooter2: require('./imgs/bannerFooter2.png'),
    bannerFooter3: require('./imgs/bannerFooter3.png'),
    twitter: require('./imgs/twiter.png'),
    youtube: require('./imgs/youtube.png')
};
export default images;
